#!/bin/sh

# TODO check more complete conf
# https://github.com/kzar/davemail/blob/master/postsync.py
# https://copyninja.info/blog/email_setup.html

PATH="/usr/local/bin:$PATH"

MBSYNC=$(pgrep mbsync)
NOTMUCH=$(pgrep notmuch)

if [ -n "$MBSYNC" -o -n "$NOTMUCH" ]; then
  echo "Already running one instance of mail-sync. Exiting..."
  exit 0
fi


# Retreive emails
mbsync -aV

# Index them
notmuch new
