section: screens
	sikaru:
	torpedo:
end

section: links
	sikaru:
		right = torpedo
	torpedo:
		left = sikaru
end

section: aliases
	sikaru:
		sikaru.home.arpa
	torpedo:
		torpedo.home.arpa
end

section: options
	heartbeat = 5000
	keystroke(super+alt+s) = switchToScreen(sikaru)
	keystroke(super+alt+t) = switchToScreen(torpedo)
	switchCorners = top-left top-right
	switchCornerSize = 5
	relativeMouseMoves = false
end
