#!/bin/sh

## Disable beeps
xset -b &

## DPMS monitor setting (standby -> suspend -> off) (seconds)
xset dpms 300 600 900 &

## Set LCD brightness
xbacklight -set 90 &

## Keybord layout setting
setxkbmap us -option 'compose:ralt' &

## Load Xmodmap conf
#xmodmap -e "remove Lock = Caps_Lock"
#xmodmap -e "keysym Caps_Lock = Control_L"
#xmodmap -e "add Control = Control_L"
xmodmap ~/.Xmodmap &

## Load Xresources
xmxrdb -load ~/.Xresources &

## OSD
dunst &
