#!/bin/bash

# this is a simple config for herbstluftwm

hc() {
  herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid black

# Fixed using export _JAVA_AWT_WM_NONREPARENTING=1 in /etc/profile.d/jre.sh
# hc set wmname LG3D

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod3   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn terminology
hc keybind $Mod-space spawn rofi -rnow
#hc keybind $Mod-space spawn dmenu_run

# basic movement
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# ???
hc keybind $Mod-Shift-r rotate

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-t cycle_layout 1
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# tags
tag_names=( {1..7} )
tag_keys=( {1..7} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
  hc add "${tag_names[$i]}"
  key="${tag_keys[$i]}"
  if ! [ -z "$key" ] ; then
    hc keybind "$Mod-$key" use_index "$i"
    hc keybind "$Mod-Shift-$key" move_index "$i"
  fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
herbstclient set focus_follows_mouse 1
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 4

hc attr theme.border_width 3
hc attr theme.inner_width 1

hc attr theme.inner_color black
hc attr theme.background_color '#141414'

hc attr theme.active.color '#4B00BC'
hc attr theme.active.inner_color '#0A42E4'
hc attr theme.active.outer_color '#F16E08'

hc attr theme.normal.color '#454545'

hc attr theme.urgent.color orange

hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black

# colors

#hc set window_border_width 1

hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#AC9F8F'

hc set frame_border_active_color '#1793D0'
hc set frame_border_normal_color '#123456'

hc set window_border_normal_color '#123456'
hc set window_border_active_color '#1793D0'

hc set window_gap 5
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F

# Generic
hc rule instance=findDialog_popup pseudotile=on focus=on
hc rule class=Conky manage=off

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole|Terminator)' focus=on

# Applications
hc rule class=URxvt tag=1
hc rule class=Terminator tag=1
hc rule class=Chromium tag=2
hc rule class=Firefox tag=2
hc rule class=Revelation tag=3
hc rule class=JDownloader tag=5

# JDownloader
hc rule title="Please confirm" pseudotile=on
hc rule title="Add URL(s)" pseudotile=on
hc rule title="Terms of Service are not accepted" pseudotile=on
hc rule title="Deep Decryption?" pseudotile=on

# Pidgin
imtag=4 # just set the name of the tag here
hc load "$imtag" '(split horizontal:0.800000:0 (clients grid:0) (clients vertical:0))'
hc rule class=Pidgin   windowrole=buddy_list tag=$imtag index=1 focus=off
hc rule class=Pidgin ! windowrole=buddy_list tag=$imtag index=0

# normally focus new clients
hc rule focus=on

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1920x1200+0+0 1920x1200+1920+0
# or simply:
hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
  # start it on each monitor
  "$panel" $monitor &
done
