#!/bin/sh

SCRIPT_DIR="$(readlink -m $(dirname $0))"
PATH="$SCRIPT_DIR:$PATH"

~/.config/bspwm/panel &

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

#bspc monitor -d I II III IV V VI VII VIII IX X

# Left
bspc monitor DVI-I-2 -d I II III
# Right
bspc monitor DVI-I-3 -d IV V VI

bspc config -m DVI-I-3 top_padding 6

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a urxvt desktop=^1
bspc rule -a Terminator desktop=^1
bspc rule -a Chromium desktop=^5
bspc rule -a Epiphany desktop=^5
bspc rule -a Firefox desktop=^5
bspc rule -a Revelation desktop=^2
bspc rule -a JDownloader desktop=^6
bspc rule -a Pidgin desktop=^5
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
