#!/bin/sh

SCRIPT_DIR="$(readlink -m $(dirname $0))"
PATH="$SCRIPT_DIR:$PATH"

if [ $(pgrep -cx panel) -gt 1 ] ; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# https://github.com/windelicato/dotfiles/blob/master/.config/bspwm/panel/panel
#bspc config top_padding $PANEL_HEIGHT
bspc config -m DVI-I-2 top_padding $PANEL_HEIGHT
bspc config -m DVI-I-3 top_padding 0
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
echo "M$(mpc current)" > "$PANEL_FIFO" &
clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &
#conky -c ~/.config/bspwm/panel_conky > "$PANEL_FIFO" &
notify_mpd -d &

cat "$PANEL_FIFO" \
  | panel_bar \
  | bar \
    -g 1920x$PANEL_HEIGHT \
    -f "$PANEL_FONT_FAMILY" \
    -F "$COLOR_FOREGROUND" \
    -B "$COLOR_BACKGROUND" &

wait
