export ZPLUG_HOME=~/.zplug

# Setup pyenv
if (( $+commands[pyenv] )); then
  export PYENV_ROOT="${ZPLUG_HOME}/repos/pyenv/pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init --path)"
fi
