#!/bin/sh

set -eu

# Tag all new messages using afew
# https://afew.readthedocs.io/en/latest/quickstart.html
# XXX: use --all as otherwise sent mails are not properly identified
# XXX: may only be required when they are added locally, not when added by the
# remote server like for Gmail
# afew --tag --all --verbose
afew --tag --new
